### ISSUE TITLE
New dico pushé sur V2, comment pusher aussi sur Dev et Master

### ISSUE THREAD

**Issue by 3rd-KaTZe** [3rd-KaTZe/Link#16]
Voir avec Etcher comment pusher une modif sur plusieures branches ?

**Comment by ghost** [comment]
Une possibilité:

commit(message) [develop] -> dernière version sur develop, master est en
retard
checkout(master) -> passage sur master
merge(develop) -> fusion des changements de "develop" dans "master"

Les options avec SmartGit:

fast-forward: develop peut être atteint en descendant la branche à partir
de master, rien à faire si ce n'est déplacer le pointeur de master
commit-merge: fusion des différences de develop dans le répertoire de
travail puis commit, dans le style 'merge changes fom origin/develop'
commit-rebase: intégration de tous les commits faits sur "develop" depuis
la divergence (greffon de la branche depuis le dernier noeud commun)
